title:              Anika Zatschler's Portfolio
email:              anika.zatschler@gmail.com
description:        My Data Science Portfolio.
author:             Anika Zatschler
baseurl:            ""
url:                "https://anikazat.github.io"

# Social Profiles
twitter_username:   
github_username:    anikazat
facebook_username:  
instagram_username:  
linkedin_username:  anika-zatschler

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
